In [4]:
import sys
import warnings
warnings.filterwarnings("ignore")

sys.path.append('../../../batchflow')

from batchflow import Config

In [24]:
pep = Config([('a', 1), ('b/a', 2), ('b', 3), ('a/b', 4)])

In [25]:
pep

Config({'a': {'b': 4}, 'b': 3})

In [78]:
def test_init():
    dict_input = {'a' : 1, 'b/a' : 2, 'b' : 3, 'a/b' : 4}
    processed_config = Config(dict_input)
    expected_config = Config({'a/b' : 4, 'b' : 3})
    assert expected_config.config == processed_config.config

In [2]:
(1,2)[0]

1

In [23]:
inputs = [Config({'a/b' : 0, 'b' : 1})]

In [24]:
a = inputs[0]

In [25]:
inputs[0].flatten()

{'a/b': 0, 'b': 1}

In [9]:
variation = 0
inputs = [Config({'a' : 0, 'b' : 1})]
expects = [(Config({'b' : 1}), 'a', 0)]
processed_return = inputs[variation].pop(expects[variation][1])
expected_return = expects[variation][2]
processed_config = inputs[variation]
expected_config = expects[variation][0]

In [10]:
processed_config

0

In [11]:
expected_config

Config({'b': 1})

In [29]:
import numpy as np

In [34]:
origin = np.random.choice((0,255), size=(3,1000,1000))
origin

array([[[  0,   0,   0, ..., 255,   0, 255],
        [255, 255,   0, ..., 255,   0, 255],
        [255,   0, 255, ...,   0,   0, 255],
        ...,
        [255,   0, 255, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0, 255],
        [255, 255,   0, ...,   0, 255, 255]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [255, 255,   0, ...,   0,   0, 255],
        [  0, 255,   0, ...,   0,   0,   0],
        ...,
        [255, 255,   0, ..., 255, 255, 255],
        [255, 255, 255, ...,   0, 255, 255],
        [  0,   0, 255, ..., 255,   0, 255]],

       [[  0, 255,   0, ...,   0, 255,   0],
        [  0,   0, 255, ..., 255,   0,   0],
        [  0,   0,   0, ...,   0,   0, 255],
        ...,
        [  0, 255, 255, ...,   0,   0, 255],
        [255,   0,   0, ...,   0, 255,   0],
        [  0, 255,   0, ..., 255,   0, 255]]])

In [35]:
divided = origin // 255 
divided

array([[[0, 0, 0, ..., 1, 0, 1],
        [1, 1, 0, ..., 1, 0, 1],
        [1, 0, 1, ..., 0, 0, 1],
        ...,
        [1, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [1, 1, 0, ..., 0, 1, 1]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 1],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 1, 1, 1],
        [1, 1, 1, ..., 0, 1, 1],
        [0, 0, 1, ..., 1, 0, 1]],

       [[0, 1, 0, ..., 0, 1, 0],
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 1, 1, ..., 0, 0, 1],
        [1, 0, 0, ..., 0, 1, 0],
        [0, 1, 0, ..., 1, 0, 1]]])

In [40]:
divided[0]*4+divided[1]*2+divided[2]

array([[0, 1, 0, ..., 4, 1, 4],
       [6, 6, 1, ..., 5, 0, 6],
       [4, 2, 4, ..., 0, 0, 5],
       ...,
       [6, 3, 5, ..., 2, 2, 3],
       [3, 2, 2, ..., 0, 3, 6],
       [4, 5, 2, ..., 3, 4, 7]])

In [73]:
n = 3
origin = np.random.choice((0,255), size=(3,1000,1000))
converter = 2 ** np.reshape(np.arange(n), (3,1,1))
(origin // 255 * converter).sum(axis=0)

array([[3, 4, 0, ..., 1, 6, 6],
       [7, 5, 2, ..., 2, 2, 2],
       [3, 1, 0, ..., 1, 3, 4],
       ...,
       [5, 7, 3, ..., 7, 1, 7],
       [2, 5, 0, ..., 6, 5, 6],
       [0, 1, 5, ..., 1, 2, 6]])

In [29]:
inputs = [(Config({'a' : 1, 'b' : 2}), Config({'b' : 3, 'c' : 4}))]
expects = [Config({'a' : 1, 'b' : 3, 'c' : 4})]

In [32]:
inputs[0][0]+inputs[0][1]

Config({'a': 1, 'b': 3, 'c': 4})

In [33]:
inputs[0]

(Config({'a': 1, 'b': 2}), Config({'b': 3, 'c': 4}))

In [52]:
a = Config({'a':{'b':1, 'c':2}})
a

Config({'a': {'b': 1, 'c': 2}})

In [54]:
a.values(True)

dict_values([1, 2])

In [46]:
for key in a.keys(True):
    print(key)

a/b
a/c


In [55]:
a

Config({'a': {'b': 1, 'c': 2}})

In [59]:
for i in iter(a)

ValueError: not enough values to unpack (expected 2, got 1)

In [60]:
Config([('a', [('b', 1), ('c', 2)]), ('d', 3)])

Config({'a': [('b', 1), ('c', 2)], 'd': 3})

In [72]:
a = Config({'a' : {}, 'b' : 0})
a

Config({'a': {}, 'b': 0})

In [73]:
b = Config(a.config)
b

Config({'a': {}, 'b': 0})

In [74]:
a.pop('a')

{}

In [75]:
a

Config({'b': 0})

In [76]:
b

Config({'a': {}, 'b': 0})

In [83]:
Config({'a':{'b':1, 'c':2}}).items(True)

dict_items([('a/b', 1), ('a/c', 2)])

In [81]:
('a', {'b': 1, 'c': 2}.items())

('a', dict_items([('b', 1), ('c', 2)]))

In [ ]:
[('a', {'b': 1, 'c': 2})].items

In [85]:
{'a' : {'c' : 'd'}}

{'a': {'c': 'd'}}