In [1]:
import sys
import warnings
warnings.filterwarnings("ignore")

sys.path.append('../../../batchflow')

from batchflow import Config

In [24]:
pep = Config([('a', 1), ('b/a', 2), ('b', 3), ('a/b', 4)])

In [25]:
pep

Config({'a': {'b': 4}, 'b': 3})

In [78]:
def test_init():
    dict_input = {'a' : 1, 'b/a' : 2, 'b' : 3, 'a/b' : 4}
    processed_config = Config(dict_input)
    expected_config = Config({'a/b' : 4, 'b' : 3})
    assert expected_config.config == processed_config.config

True

{'a': {'b': 4}, 'b': 3}

In [29]:
import numpy as np

In [34]:
origin = np.random.choice((0,255), size=(3,1000,1000))
origin

array([[[  0,   0,   0, ..., 255,   0, 255],
        [255, 255,   0, ..., 255,   0, 255],
        [255,   0, 255, ...,   0,   0, 255],
        ...,
        [255,   0, 255, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0, 255],
        [255, 255,   0, ...,   0, 255, 255]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [255, 255,   0, ...,   0,   0, 255],
        [  0, 255,   0, ...,   0,   0,   0],
        ...,
        [255, 255,   0, ..., 255, 255, 255],
        [255, 255, 255, ...,   0, 255, 255],
        [  0,   0, 255, ..., 255,   0, 255]],

       [[  0, 255,   0, ...,   0, 255,   0],
        [  0,   0, 255, ..., 255,   0,   0],
        [  0,   0,   0, ...,   0,   0, 255],
        ...,
        [  0, 255, 255, ...,   0,   0, 255],
        [255,   0,   0, ...,   0, 255,   0],
        [  0, 255,   0, ..., 255,   0, 255]]])

In [35]:
divided = origin // 255 
divided

array([[[0, 0, 0, ..., 1, 0, 1],
        [1, 1, 0, ..., 1, 0, 1],
        [1, 0, 1, ..., 0, 0, 1],
        ...,
        [1, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [1, 1, 0, ..., 0, 1, 1]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 1],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 1, 1, 1],
        [1, 1, 1, ..., 0, 1, 1],
        [0, 0, 1, ..., 1, 0, 1]],

       [[0, 1, 0, ..., 0, 1, 0],
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 1, 1, ..., 0, 0, 1],
        [1, 0, 0, ..., 0, 1, 0],
        [0, 1, 0, ..., 1, 0, 1]]])

In [40]:
divided[0]*4+divided[1]*2+divided[2]

array([[0, 1, 0, ..., 4, 1, 4],
       [6, 6, 1, ..., 5, 0, 6],
       [4, 2, 4, ..., 0, 0, 5],
       ...,
       [6, 3, 5, ..., 2, 2, 3],
       [3, 2, 2, ..., 0, 3, 6],
       [4, 5, 2, ..., 3, 4, 7]])

In [73]:
n = 3
origin = np.random.choice((0,255), size=(3,1000,1000))
converter = 2 ** np.reshape(np.arange(n), (3,1,1))
(origin // 255 * converter).sum(axis=0)

array([[3, 4, 0, ..., 1, 6, 6],
       [7, 5, 2, ..., 2, 2, 2],
       [3, 1, 0, ..., 1, 3, 4],
       ...,
       [5, 7, 3, ..., 7, 1, 7],
       [2, 5, 0, ..., 6, 5, 6],
       [0, 1, 5, ..., 1, 2, 6]])